# 0表示按cpu核数创建工作器
worker_mgr:
    num: 0

io_context_mgr:
    num: 1

module:
    dirs: 
        - ../../lib/Debug
    loads:
        - db
        - pysvr
        - gateway

timer:
    ms_per_tick: 10
    
session_monitor:
    timeout_s: 10
    tick_s: 1
    
gateway:
    services:
        - port:10086