# Million框架配置示例 - 支持基于异步架构的EtcdService

# 节点配置
node:
  id: 1

# 工作线程配置
worker_mgr:
  num: 4  # 工作线程数量

# IO线程配置 - etcd模块将使用这些IO线程进行异步操作
io_context_mgr:
  num: 2  # IO线程数量，etcd异步操作将在这些线程中执行，避免阻塞Service线程

# 会话监控配置
session_monitor:
  s_per_tick: 1
  timeout_tick: 30

# 定时器配置
timer:
  ms_per_tick: 100

# Etcd配置 - 异步非阻塞架构
etcd:
  endpoints: "http://127.0.0.1:2379"        # etcd服务器地址
  heartbeat_check_interval_ms: 30000        # 心跳状态检查间隔(毫秒，可选)
  # 说明：
  # - 所有etcd操作现在都是异步的，不会阻塞Service线程
  # - 使用etcd::Client替代SyncClient，在IO线程中执行操作
  # - Watcher事件通过asio::post安全传递到Service线程
  # - 服务注册使用etcd租约和KeepAlive自动维持心跳

# 模块配置
module_mgr:
  - dir: "module"
    loads:
      - "etcd"      # 加载etcd模块（异步版本）
      - "config"    # 配置模块
      - "logger"    # 日志模块 