// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: csguild.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_csguild_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_csguild_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
#include "csmsgid.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_csguild_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_csguild_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_csguild_2eproto;
namespace Cs {
class GuildCreateReq;
struct GuildCreateReqDefaultTypeInternal;
extern GuildCreateReqDefaultTypeInternal _GuildCreateReq_default_instance_;
}  // namespace Cs
PROTOBUF_NAMESPACE_OPEN
template<> ::Cs::GuildCreateReq* Arena::CreateMaybeMessage<::Cs::GuildCreateReq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Cs {

enum SubMsgIdGuild : int {
  SUB_MSG_ID_GUILD_INVALID = 0,
  SUB_MSG_ID_GUILD_CREATE = 1,
  SubMsgIdGuild_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  SubMsgIdGuild_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool SubMsgIdGuild_IsValid(int value);
constexpr SubMsgIdGuild SubMsgIdGuild_MIN = SUB_MSG_ID_GUILD_INVALID;
constexpr SubMsgIdGuild SubMsgIdGuild_MAX = SUB_MSG_ID_GUILD_CREATE;
constexpr int SubMsgIdGuild_ARRAYSIZE = SubMsgIdGuild_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SubMsgIdGuild_descriptor();
template<typename T>
inline const std::string& SubMsgIdGuild_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SubMsgIdGuild>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SubMsgIdGuild_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SubMsgIdGuild_descriptor(), enum_t_value);
}
inline bool SubMsgIdGuild_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SubMsgIdGuild* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SubMsgIdGuild>(
    SubMsgIdGuild_descriptor(), name, value);
}
// ===================================================================

class GuildCreateReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Cs.GuildCreateReq) */ {
 public:
  inline GuildCreateReq() : GuildCreateReq(nullptr) {}
  ~GuildCreateReq() override;
  explicit PROTOBUF_CONSTEXPR GuildCreateReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GuildCreateReq(const GuildCreateReq& from);
  GuildCreateReq(GuildCreateReq&& from) noexcept
    : GuildCreateReq() {
    *this = ::std::move(from);
  }

  inline GuildCreateReq& operator=(const GuildCreateReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline GuildCreateReq& operator=(GuildCreateReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GuildCreateReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const GuildCreateReq* internal_default_instance() {
    return reinterpret_cast<const GuildCreateReq*>(
               &_GuildCreateReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GuildCreateReq& a, GuildCreateReq& b) {
    a.Swap(&b);
  }
  inline void Swap(GuildCreateReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GuildCreateReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GuildCreateReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GuildCreateReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GuildCreateReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GuildCreateReq& from) {
    GuildCreateReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GuildCreateReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Cs.GuildCreateReq";
  }
  protected:
  explicit GuildCreateReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGuildNameFieldNumber = 1,
  };
  // string guild_name = 1;
  void clear_guild_name();
  const std::string& guild_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_guild_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_guild_name();
  PROTOBUF_NODISCARD std::string* release_guild_name();
  void set_allocated_guild_name(std::string* guild_name);
  private:
  const std::string& _internal_guild_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_guild_name(const std::string& value);
  std::string* _internal_mutable_guild_name();
  public:

  // @@protoc_insertion_point(class_scope:Cs.GuildCreateReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr guild_name_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_csguild_2eproto;
};
// ===================================================================

static const int kCsSubMsgIdGuildFieldNumber = 11001;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::Cs::SubMsgIdGuild, ::Cs::SubMsgIdGuild_IsValid>, 14, false >
  cs_sub_msg_id_guild;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GuildCreateReq

// string guild_name = 1;
inline void GuildCreateReq::clear_guild_name() {
  _impl_.guild_name_.ClearToEmpty();
}
inline const std::string& GuildCreateReq::guild_name() const {
  // @@protoc_insertion_point(field_get:Cs.GuildCreateReq.guild_name)
  return _internal_guild_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GuildCreateReq::set_guild_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.guild_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Cs.GuildCreateReq.guild_name)
}
inline std::string* GuildCreateReq::mutable_guild_name() {
  std::string* _s = _internal_mutable_guild_name();
  // @@protoc_insertion_point(field_mutable:Cs.GuildCreateReq.guild_name)
  return _s;
}
inline const std::string& GuildCreateReq::_internal_guild_name() const {
  return _impl_.guild_name_.Get();
}
inline void GuildCreateReq::_internal_set_guild_name(const std::string& value) {
  
  _impl_.guild_name_.Set(value, GetArenaForAllocation());
}
inline std::string* GuildCreateReq::_internal_mutable_guild_name() {
  
  return _impl_.guild_name_.Mutable(GetArenaForAllocation());
}
inline std::string* GuildCreateReq::release_guild_name() {
  // @@protoc_insertion_point(field_release:Cs.GuildCreateReq.guild_name)
  return _impl_.guild_name_.Release();
}
inline void GuildCreateReq::set_allocated_guild_name(std::string* guild_name) {
  if (guild_name != nullptr) {
    
  } else {
    
  }
  _impl_.guild_name_.SetAllocated(guild_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.guild_name_.IsDefault()) {
    _impl_.guild_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Cs.GuildCreateReq.guild_name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Cs

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Cs::SubMsgIdGuild> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Cs::SubMsgIdGuild>() {
  return ::Cs::SubMsgIdGuild_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_csguild_2eproto
