// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: csmsgid.proto

#include "csmsgid.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Cs {
}  // namespace Cs
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_csmsgid_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_csmsgid_2eproto = nullptr;
const uint32_t TableStruct_csmsgid_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_csmsgid_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rcsmsgid.proto\022\002Cs\032 google/protobuf/des"
  "criptor.proto*A\n\005MsgId\022\022\n\016MSG_ID_INVALID"
  "\020\000\022\020\n\014MSG_ID_GUILD\020\001\022\022\n\016MSG_ID_PACKAGE\020\002"
  ":;\n\tcs_msg_id\022\034.google.protobuf.EnumOpti"
  "ons\030\221N \001(\0162\t.Cs.MsgIdb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_csmsgid_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::_pbi::once_flag descriptor_table_csmsgid_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_csmsgid_2eproto = {
    false, false, 189, descriptor_table_protodef_csmsgid_2eproto,
    "csmsgid.proto",
    &descriptor_table_csmsgid_2eproto_once, descriptor_table_csmsgid_2eproto_deps, 1, 0,
    schemas, file_default_instances, TableStruct_csmsgid_2eproto::offsets,
    nullptr, file_level_enum_descriptors_csmsgid_2eproto,
    file_level_service_descriptors_csmsgid_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_csmsgid_2eproto_getter() {
  return &descriptor_table_csmsgid_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_csmsgid_2eproto(&descriptor_table_csmsgid_2eproto);
namespace Cs {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MsgId_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_csmsgid_2eproto);
  return file_level_enum_descriptors_csmsgid_2eproto[0];
}
bool MsgId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::EnumOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::Cs::MsgId, ::Cs::MsgId_IsValid>, 14, false>
  cs_msg_id(kCsMsgIdFieldNumber, static_cast< ::Cs::MsgId >(0), nullptr);

// @@protoc_insertion_point(namespace_scope)
}  // namespace Cs
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
