// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cspackage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cspackage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cspackage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
#include "csmsgid.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cspackage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cspackage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cspackage_2eproto;
namespace Cs {
class PackageOpenReq;
struct PackageOpenReqDefaultTypeInternal;
extern PackageOpenReqDefaultTypeInternal _PackageOpenReq_default_instance_;
}  // namespace Cs
PROTOBUF_NAMESPACE_OPEN
template<> ::Cs::PackageOpenReq* Arena::CreateMaybeMessage<::Cs::PackageOpenReq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Cs {

enum SubMsgIdPackage : int {
  SUB_MSG_ID_PACKAGE_INVALID = 0,
  SUB_MSG_ID_PACKAGE_OPEN = 1,
  SubMsgIdPackage_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  SubMsgIdPackage_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool SubMsgIdPackage_IsValid(int value);
constexpr SubMsgIdPackage SubMsgIdPackage_MIN = SUB_MSG_ID_PACKAGE_INVALID;
constexpr SubMsgIdPackage SubMsgIdPackage_MAX = SUB_MSG_ID_PACKAGE_OPEN;
constexpr int SubMsgIdPackage_ARRAYSIZE = SubMsgIdPackage_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SubMsgIdPackage_descriptor();
template<typename T>
inline const std::string& SubMsgIdPackage_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SubMsgIdPackage>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SubMsgIdPackage_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SubMsgIdPackage_descriptor(), enum_t_value);
}
inline bool SubMsgIdPackage_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SubMsgIdPackage* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SubMsgIdPackage>(
    SubMsgIdPackage_descriptor(), name, value);
}
// ===================================================================

class PackageOpenReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Cs.PackageOpenReq) */ {
 public:
  inline PackageOpenReq() : PackageOpenReq(nullptr) {}
  ~PackageOpenReq() override;
  explicit PROTOBUF_CONSTEXPR PackageOpenReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PackageOpenReq(const PackageOpenReq& from);
  PackageOpenReq(PackageOpenReq&& from) noexcept
    : PackageOpenReq() {
    *this = ::std::move(from);
  }

  inline PackageOpenReq& operator=(const PackageOpenReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline PackageOpenReq& operator=(PackageOpenReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PackageOpenReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const PackageOpenReq* internal_default_instance() {
    return reinterpret_cast<const PackageOpenReq*>(
               &_PackageOpenReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PackageOpenReq& a, PackageOpenReq& b) {
    a.Swap(&b);
  }
  inline void Swap(PackageOpenReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PackageOpenReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PackageOpenReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PackageOpenReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PackageOpenReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PackageOpenReq& from) {
    PackageOpenReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PackageOpenReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Cs.PackageOpenReq";
  }
  protected:
  explicit PackageOpenReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTabFieldNumber = 1,
  };
  // int32 tab = 1;
  void clear_tab();
  int32_t tab() const;
  void set_tab(int32_t value);
  private:
  int32_t _internal_tab() const;
  void _internal_set_tab(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Cs.PackageOpenReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t tab_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cspackage_2eproto;
};
// ===================================================================

static const int kCsSubMsgIdPackageFieldNumber = 11002;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::Cs::SubMsgIdPackage, ::Cs::SubMsgIdPackage_IsValid>, 14, false >
  cs_sub_msg_id_package;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PackageOpenReq

// int32 tab = 1;
inline void PackageOpenReq::clear_tab() {
  _impl_.tab_ = 0;
}
inline int32_t PackageOpenReq::_internal_tab() const {
  return _impl_.tab_;
}
inline int32_t PackageOpenReq::tab() const {
  // @@protoc_insertion_point(field_get:Cs.PackageOpenReq.tab)
  return _internal_tab();
}
inline void PackageOpenReq::_internal_set_tab(int32_t value) {
  
  _impl_.tab_ = value;
}
inline void PackageOpenReq::set_tab(int32_t value) {
  _internal_set_tab(value);
  // @@protoc_insertion_point(field_set:Cs.PackageOpenReq.tab)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Cs

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Cs::SubMsgIdPackage> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Cs::SubMsgIdPackage>() {
  return ::Cs::SubMsgIdPackage_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cspackage_2eproto
